export const categories = [
  {
    id: 1,
    img: 'https://images.unsplash.com/photo-1604975701397-6365ccbd028a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Y2luZW1hfGVufDB8MXwwfHw%3D&auto=format&fit=crop&w=500&q=60',
    title: 'MOVIES',
    cat: 'Movies',
  },
  {
    id: 2,
    img: 'https://images.unsplash.com/photo-1580247817119-c6cb496270a4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dHYlMjBzZXJpZXN8ZW58MHwxfDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
    title: 'TV SERIES',
    cat: 'TV Series',
  },
  {
    id: 3,
    img: 'https://images.unsplash.com/photo-1597910037310-7dd8ddb93e24?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjJ8fGRpc2NvdmVyeXxlbnwwfDF8MHx8&auto=format&fit=crop&w=500&q=60',
    title: 'DOCUMENTARIES',
    cat: 'Documentaries',
  },
];

export const popularProducts = [
  {
    id: 1,
    title: 'America 3000',
    img: 'https://freeclassicimages.com/images/America-3000-01-movie-poster.jpg',
    genre: ['Action', 'Comedy'],
    crew: ['Chuck Wagner', 'Laurene Landon', 'William Wallace'],
    runtime: '92 minutes',
    desc: 'In Colorado, 900 years after a nuclear war in the USA, humanitys been sent back to the Stone Age lifestyle. Amazons are ruling the tribes, the men are dumb, either kept as slaves and sex partners, or are living wild as animals. Only Korvis and a friend are intelligent enough to flee and found a tribe of their own. Will they manage to teach the women love to men again?',
    category: 'Movies',
  },
  {
    id: 2,
    title: 'My Fair lady',
    img: 'https://freeclassicimages.com/images/my-fair-lady.jpg',
    genre: ['Drama', 'Musical'],
    crew: ['Eliza Doolittle', 'Prof. Henry Higgins', 'Alfred P.Doolittle '],
    runtime: '23 minutes',
    desc: 'Pompous phonetics Professor Henry Higgins (Sir Rex Harrison) is so sure of his abilities that he takes it upon himself to transform a Cockney working-class girl into someone who can pass for a cultured member of high society. His subject turns out to be the lovely Eliza Doolittle (Audrey Hepburn), who agrees to speech lessons to improve her job prospects. Higgins and Eliza clash, then form an unlikely bond, one that is threatened by aristocratic suitor Freddy Eynsford-Hill (Jeremy Brett).',
    category: 'TV Series',
  },
  {
    id: 3,
    title: '13 Ghosts',
    img: 'https://freeclassicimages.com/images/13-Ghosts-01-movie-poster.jpg',
    genre: ['Horror'],
    crew: ['Charles Herbert', 'Jo Morrow', 'Martin Milner'],
    runtime: '85 minutes',
    desc: 'Reclusive Dr. Zorba has died and left his eerie mansion to his penniless nephew Cyrus Zorba and his family. Along with the house, the Zorba family has also inherited the occultists collection of 13 ghosts, who can only be seen through Zorbas special goggles. The family members, their lives at risk upon the discovery that Dr. Zorbas fortune lies hidden somewhere in the house, receive aid from unexpected quarters as the threat to their lives is revealed.',
    category: 'Movies',
  },
  {
    id: 4,
    title: '20 Million Miles To Earth',
    img: 'https://freeclassicimages.com/images/20-Million-Miles-To-Earth-01-movie-poster.jpg',
    genre: ['Adventure', 'Fantasy'],
    crew: ['William Hopper', 'Joan Taylor'],
    runtime: '60 minutes',
    desc: 'N/A',
    category: 'TV Series',
  },
  {
    id: 5,
    title: 'Walking With Dinosaur',
    img: 'https://images.unsplash.com/photo-1534534502714-2828e7c540d0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fGRpbm9zYXVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
    genre: ['History'],
    crew: ['Kenneth Branagh'],
    runtime: '90 minutes',
    desc: 'Using the latest technology the amazing lost world of the Cretaceous, Triassic and Jurassic periods of Earths history, when the dinosaurs reigned supreme, is brought stunningly back to life. The series provides insights into how these mammoth creatures appeared, how they survived for millions of years and probes the mysteries of their sudden disappearance leaving only a fossil record to show they had ever existed!',
    category: 'Documentaries',
  },
  {
    id: 6,
    title: '48 Hours',
    img: 'https://freeclassicimages.com/images/48_hrs_1982.jpg',
    genre: ['Action', 'Comedy'],
    crew: ['Nick Nolte', 'Eddie Murphy'],
    runtime: '96 minutes',
    desc: 'Oddball cop and tough guy, Jack Cates is the only survivor of a cop shooting and in hunting down the murderer collects Reggie Hammond from jail for 48 hours. Hammond is oddly motivated to help. The killer is searching for his stash of cash. Cates and Hammond who have the Black-white, cop-crook thing to work out make surprisingly good partners as they navigate through the city looking for their suspect.',
    category: 'Movies',
  },
  {
    id: 7,
    title: '40 Winks',
    img: 'https://freeclassicimages.com/images/40-Winks-1925-1A3-movie-poster.jpg',
    genre: ['Romance'],
    crew: ['Viola Dana', 'Raymond Griffith', 'Theodore Roberts'],
    runtime: '60 minutes',
    desc: 'N/A',
    category: 'Movies',
  },
  {
    id: 8,
    title: 'The 3 Stooges',
    img: 'https://freeclassicimages.com/images/3-stooges-1941-movie-poster.jpg',
    genre: ['Comedy'],
    crew: ['3 Stooges'],
    runtime: '30 minutes',
    desc: 'The Three Stooges were an American vaudeville and comedy team active from 1922 until 1970, best known for their 190 short subject films by Columbia Pictures that have been regularly airing on television since 1958. Their hallmark was physical farce and slapstick.',
    category: 'TV Series',
  },
];
